// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module v_tpg_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        height,
        width,
        bckgndId,
        ZplateHorContStart,
        ZplateHorContDelta,
        ZplateVerContStart,
        ZplateVerContDelta,
        dpDynamicRange,
        dpYUVCoef,
        motionSpeed,
        colorFormat,
        bckgndYUV_din,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_full_n,
        bckgndYUV_write,
        s
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] height;
input  [15:0] width;
input  [7:0] bckgndId;
input  [15:0] ZplateHorContStart;
input  [15:0] ZplateHorContDelta;
input  [15:0] ZplateVerContStart;
input  [15:0] ZplateVerContDelta;
input  [7:0] dpDynamicRange;
input  [7:0] dpYUVCoef;
input  [7:0] motionSpeed;
input  [7:0] colorFormat;
output  [23:0] bckgndYUV_din;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg start_write;
reg bckgndYUV_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] rampStart;
reg   [15:0] rampVal_1;
reg   [7:0] rampVal;
reg   [7:0] hBarSel_2;
reg   [15:0] zonePlateVAddr;
reg   [2:0] vBarSel;
reg   [2:0] hBarSel;
reg   [15:0] hdata;
reg   [7:0] vBarSel_2;
reg   [2:0] hBarSel_3;
reg   [15:0] rampVal_2;
reg   [0:0] vBarSel_1;
reg   [2:0] hBarSel_1;
wire   [0:0] cmp2_i321_fu_629_p2;
reg   [0:0] cmp2_i321_reg_1298;
wire   [7:0] conv2_i_i10_i326_fu_635_p3;
reg   [7:0] conv2_i_i10_i326_reg_1303;
wire   [0:0] not_cmp2_i321_fu_643_p2;
reg   [0:0] not_cmp2_i321_reg_1308;
wire   [7:0] conv2_i_i10_i331_fu_649_p3;
reg   [7:0] conv2_i_i10_i331_reg_1313;
wire   [4:0] conv2_i_i_i333_cast_cast_fu_657_p3;
reg   [4:0] conv2_i_i_i333_cast_cast_reg_1318;
wire   [2:0] conv2_i_i10_i349_cast_cast_cast_cast_fu_665_p3;
reg   [2:0] conv2_i_i10_i349_cast_cast_cast_cast_reg_1323;
wire   [7:0] conv2_i_i_i351_fu_673_p3;
reg   [7:0] conv2_i_i_i351_reg_1328;
wire   [7:0] pix_val_V_fu_681_p3;
reg   [7:0] pix_val_V_reg_1333;
wire   [7:0] pix_val_V_5_fu_689_p3;
reg   [7:0] pix_val_V_5_reg_1338;
wire   [9:0] barWidthMinSamples_fu_721_p2;
reg   [9:0] barWidthMinSamples_reg_1343;
wire   [0:0] icmp_fu_751_p2;
reg   [0:0] icmp_reg_1348;
reg   [10:0] barWidth_reg_1353;
wire   [10:0] sub_i_i_i_fu_787_p2;
reg   [10:0] sub_i_i_i_reg_1359;
wire   [16:0] sub40_i_fu_793_p2;
reg   [16:0] sub40_i_reg_1364;
wire   [16:0] add_ln1404_fu_799_p2;
reg   [16:0] add_ln1404_reg_1369;
wire   [0:0] cmp59_i_fu_805_p2;
reg   [0:0] cmp59_i_reg_1374;
wire   [0:0] cmp126_i_fu_811_p2;
reg   [0:0] cmp126_i_reg_1379;
wire   [0:0] cmp141_i_fu_817_p2;
reg   [0:0] cmp141_i_reg_1384;
reg   [7:0] rampStart_load_reg_1389;
wire   [7:0] select_ln214_fu_899_p3;
reg   [7:0] select_ln214_reg_1395;
wire   [15:0] shl_ln_fu_907_p3;
reg   [15:0] shl_ln_reg_1400;
wire   [0:0] icmp_ln1217_fu_915_p2;
reg   [0:0] icmp_ln1217_reg_1405;
reg   [15:0] y_3_reg_1410;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp12_i_fu_1004_p2;
reg   [0:0] cmp12_i_reg_1418;
wire   [0:0] icmp_ln518_fu_993_p2;
wire   [0:0] icmp_ln1404_fu_1020_p2;
reg   [0:0] icmp_ln1404_reg_1423;
wire   [0:0] icmp_ln1404_1_fu_1030_p2;
reg   [0:0] icmp_ln1404_1_reg_1428;
wire   [7:0] add_ln1488_fu_1035_p2;
reg   [7:0] add_ln1488_reg_1433;
wire   [0:0] or_ln1592_fu_1052_p2;
reg   [0:0] or_ln1592_reg_1438;
wire   [0:0] or_ln1592_1_fu_1064_p2;
reg   [0:0] or_ln1592_1_reg_1443;
wire   [0:0] or_ln1592_2_fu_1070_p2;
reg   [0:0] or_ln1592_2_reg_1448;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready;
wire   [23:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4;
reg   [0:0] rampVal_3_flag_0_reg_406;
reg    ap_block_state1;
wire    ap_CS_fsm_state5;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_422_p4;
reg   [0:0] hdata_flag_0_reg_418;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4;
reg   [0:0] rampVal_2_flag_0_reg_430;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [15:0] rampVal_3_new_0_fu_324;
reg   [15:0] rampVal_3_loc_0_fu_320;
reg   [15:0] rampVal_loc_0_fu_316;
reg   [7:0] hBarSel_4_loc_0_fu_312;
reg   [15:0] zonePlateVAddr_loc_0_fu_308;
reg   [7:0] vBarSel_loc_0_fu_304;
reg   [7:0] hBarSel_loc_0_fu_300;
reg   [15:0] hdata_new_0_fu_296;
reg   [15:0] hdata_loc_0_fu_292;
reg   [7:0] vBarSel_2_loc_0_fu_288;
reg   [7:0] hBarSel_3_loc_0_fu_284;
reg   [15:0] rampVal_2_new_0_fu_280;
reg   [15:0] rampVal_2_loc_0_fu_276;
reg   [7:0] vBarSel_3_loc_0_fu_272;
reg   [7:0] hBarSel_5_loc_0_fu_268;
reg   [7:0] p_0_2_0_0_0558_lcssa567_fu_260;
reg   [7:0] p_0_1_0_0_0556_lcssa564_fu_256;
reg   [7:0] p_0_0_0_0_0554_lcssa561_fu_252;
wire   [7:0] add_ln705_fu_1081_p2;
reg   [15:0] y_fu_264;
wire   [15:0] add_ln518_fu_998_p2;
wire   [7:0] zext_ln518_fu_895_p1;
wire   [7:0] zext_ln1730_fu_887_p1;
wire   [7:0] zext_ln1610_fu_875_p1;
wire   [7:0] zext_ln1493_fu_859_p1;
wire   [7:0] zext_ln1367_fu_851_p1;
wire   [15:0] zext_ln1212_fu_835_p1;
wire   [13:0] empty_fu_701_p1;
wire   [13:0] add2_i_fu_705_p2;
wire   [9:0] p_cast_fu_711_p4;
wire   [13:0] empty_72_fu_731_p1;
wire   [6:0] tmp_fu_741_p4;
wire   [13:0] add_i_fu_757_p2;
wire   [13:0] add5_i_fu_735_p2;
wire   [9:0] tmp_2_fu_773_p4;
wire   [10:0] barHeight_cast_cast_fu_783_p1;
wire   [16:0] loopWidth_cast15_fu_697_p1;
wire   [16:0] loopHeight_cast16_fu_727_p1;
wire   [16:0] zext_ln1404_fu_1026_p1;
wire   [7:0] trunc_ln518_fu_989_p1;
wire   [1:0] Sel_fu_1010_p4;
wire   [0:0] icmp_ln1592_fu_1040_p2;
wire   [0:0] icmp_ln1592_1_fu_1046_p2;
wire   [0:0] icmp_ln1592_2_fu_1058_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 rampStart = 8'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 8'd0;
#0 hBarSel_2 = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 vBarSel = 3'd0;
#0 hBarSel = 3'd0;
#0 hdata = 16'd0;
#0 vBarSel_2 = 8'd0;
#0 hBarSel_3 = 3'd0;
#0 rampVal_2 = 16'd0;
#0 vBarSel_1 = 1'd0;
#0 hBarSel_1 = 3'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg = 1'b0;
end

v_tpg_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_406),
    .hdata_flag_0(hdata_flag_0_reg_418),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_430),
    .loopWidth(width),
    .pix_val_V_5(pix_val_V_5_reg_1338),
    .pix_val_V(pix_val_V_reg_1333),
    .conv2_i_i_i351(conv2_i_i_i351_reg_1328),
    .conv2_i_i_i333_cast_cast(conv2_i_i_i333_cast_cast_reg_1318),
    .conv2_i_i_i_cast(not_cmp2_i321_reg_1308),
    .select_ln214(select_ln214_reg_1395),
    .conv2_i_i10_i349_cast_cast_cast_cast(conv2_i_i10_i349_cast_cast_cast_cast_reg_1323),
    .conv2_i_i10_i331(conv2_i_i10_i331_reg_1313),
    .conv2_i_i10_i326(conv2_i_i10_i326_reg_1303),
    .rampStart_1(rampStart_load_reg_1389),
    .Zplate_Hor_Control_Start(ZplateHorContStart),
    .bckgndId_load(bckgndId),
    .cmp2_i321(cmp2_i321_reg_1298),
    .zext_ln1032(rampStart_load_reg_1389),
    .y(y_3_reg_1410),
    .colorFormatLocal(colorFormat),
    .cmp141_i(cmp141_i_reg_1384),
    .icmp_ln1217(icmp_ln1217_reg_1405),
    .barWidth_cast(barWidth_reg_1353),
    .barWidth(barWidth_reg_1353),
    .shl_ln(shl_ln_reg_1400),
    .Zplate_Hor_Control_Delta(ZplateHorContDelta),
    .Zplate_Ver_Control_Start(ZplateVerContStart),
    .cmp12_i(cmp12_i_reg_1418),
    .Zplate_Ver_Control_Delta(ZplateVerContDelta),
    .sub_i_i_i(sub_i_i_i_reg_1359),
    .barWidthMinSamples(barWidthMinSamples_reg_1343),
    .icmp_ln1404_1(icmp_ln1404_1_reg_1428),
    .icmp_ln1404(icmp_ln1404_reg_1423),
    .sub40_i(sub40_i_reg_1364),
    .add_ln1488(add_ln1488_reg_1433),
    .cmp35_i526(icmp_reg_1348),
    .or_ln1592(or_ln1592_reg_1438),
    .or_ln1592_1(or_ln1592_1_reg_1443),
    .or_ln1592_2(or_ln1592_2_reg_1448),
    .cmp59_i(cmp59_i_reg_1374),
    .cmp126_i(cmp126_i_reg_1379),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_320),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_316),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld),
    .hBarSel_4_loc_1_out_i(hBarSel_4_loc_0_fu_312),
    .hBarSel_4_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o),
    .hBarSel_4_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_308),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_304),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o_ap_vld),
    .hBarSel_loc_1_out_i(hBarSel_loc_0_fu_300),
    .hBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o),
    .hBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_292),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld),
    .vBarSel_2_loc_1_out_i(vBarSel_2_loc_0_fu_288),
    .vBarSel_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o),
    .vBarSel_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o_ap_vld),
    .hBarSel_3_loc_1_out_i(hBarSel_3_loc_0_fu_284),
    .hBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o),
    .hBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_276),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld),
    .vBarSel_3_loc_1_out_i(vBarSel_3_loc_0_fu_272),
    .vBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o),
    .vBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o_ap_vld),
    .hBarSel_5_loc_1_out_i(hBarSel_5_loc_0_fu_268),
    .hBarSel_5_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o),
    .hBarSel_5_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o_ap_vld),
    .p_0_2_0_0_0557_out_i(p_0_2_0_0_0558_lcssa567_fu_260),
    .p_0_2_0_0_0557_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o),
    .p_0_2_0_0_0557_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o_ap_vld),
    .p_0_1_0_0_0555_out_i(p_0_1_0_0_0556_lcssa564_fu_256),
    .p_0_1_0_0_0555_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o),
    .p_0_1_0_0_0555_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o_ap_vld),
    .p_0_0_0_0_0553_out_i(p_0_0_0_0_0554_lcssa561_fu_252),
    .p_0_0_0_0_0553_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o),
    .p_0_0_0_0_0553_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld),
    .hBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2),
    .hBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2_ap_vld),
    .s(s),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld),
    .hBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel),
    .hBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_ap_vld),
    .hBarSel_3(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3),
    .hBarSel_3_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_ap_vld),
    .vBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2),
    .vBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_ap_vld),
    .hBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1),
    .hBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_3_loc_0_fu_284 <= zext_ln1610_fu_875_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_3_loc_0_fu_284 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_4_loc_0_fu_312 <= hBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_4_loc_0_fu_312 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_5_loc_0_fu_268 <= zext_ln518_fu_895_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_5_loc_0_fu_268 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_loc_0_fu_300 <= zext_ln1493_fu_859_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_loc_0_fu_300 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hdata_flag_0_reg_418 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_flag_0_reg_418 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_loc_0_fu_292 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_loc_0_fu_292 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_2_flag_0_reg_430 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_flag_0_reg_430 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_loc_0_fu_276 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_loc_0_fu_276 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_3_flag_0_reg_406 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_flag_0_reg_406 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_loc_0_fu_320 <= rampVal_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_3_loc_0_fu_320 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_loc_0_fu_316 <= zext_ln1212_fu_835_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_loc_0_fu_316 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_2_loc_0_fu_288 <= vBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_2_loc_0_fu_288 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_3_loc_0_fu_272 <= zext_ln1730_fu_887_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_3_loc_0_fu_272 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_loc_0_fu_304 <= zext_ln1367_fu_851_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_loc_0_fu_304 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_264 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd0))) begin
        y_fu_264 <= add_ln518_fu_998_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVAddr_loc_0_fu_308 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr_loc_0_fu_308 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln1404_reg_1369 <= add_ln1404_fu_799_p2;
        barWidthMinSamples_reg_1343 <= barWidthMinSamples_fu_721_p2;
        barWidth_reg_1353 <= {{add_i_fu_757_p2[13:3]}};
        cmp126_i_reg_1379 <= cmp126_i_fu_811_p2;
        cmp141_i_reg_1384 <= cmp141_i_fu_817_p2;
        cmp2_i321_reg_1298 <= cmp2_i321_fu_629_p2;
        cmp59_i_reg_1374 <= cmp59_i_fu_805_p2;
        conv2_i_i10_i326_reg_1303[1 : 0] <= conv2_i_i10_i326_fu_635_p3[1 : 0];
conv2_i_i10_i326_reg_1303[5 : 4] <= conv2_i_i10_i326_fu_635_p3[5 : 4];
conv2_i_i10_i326_reg_1303[7] <= conv2_i_i10_i326_fu_635_p3[7];
        conv2_i_i10_i331_reg_1313[0] <= conv2_i_i10_i331_fu_649_p3[0];
conv2_i_i10_i331_reg_1313[2] <= conv2_i_i10_i331_fu_649_p3[2];
conv2_i_i10_i331_reg_1313[4] <= conv2_i_i10_i331_fu_649_p3[4];
conv2_i_i10_i331_reg_1313[7] <= conv2_i_i10_i331_fu_649_p3[7];
        conv2_i_i10_i349_cast_cast_cast_cast_reg_1323[0] <= conv2_i_i10_i349_cast_cast_cast_cast_fu_665_p3[0];
conv2_i_i10_i349_cast_cast_cast_cast_reg_1323[2] <= conv2_i_i10_i349_cast_cast_cast_cast_fu_665_p3[2];
        conv2_i_i_i333_cast_cast_reg_1318[0] <= conv2_i_i_i333_cast_cast_fu_657_p3[0];
conv2_i_i_i333_cast_cast_reg_1318[2] <= conv2_i_i_i333_cast_cast_fu_657_p3[2];
conv2_i_i_i333_cast_cast_reg_1318[4] <= conv2_i_i_i333_cast_cast_fu_657_p3[4];
        conv2_i_i_i351_reg_1328[2] <= conv2_i_i_i351_fu_673_p3[2];
conv2_i_i_i351_reg_1328[4] <= conv2_i_i_i351_fu_673_p3[4];
conv2_i_i_i351_reg_1328[7] <= conv2_i_i_i351_fu_673_p3[7];
        icmp_ln1217_reg_1405 <= icmp_ln1217_fu_915_p2;
        icmp_reg_1348 <= icmp_fu_751_p2;
        not_cmp2_i321_reg_1308 <= not_cmp2_i321_fu_643_p2;
        pix_val_V_5_reg_1338[6 : 0] <= pix_val_V_5_fu_689_p3[6 : 0];
        pix_val_V_reg_1333[7] <= pix_val_V_fu_681_p3[7];
        rampStart_load_reg_1389 <= rampStart;
        select_ln214_reg_1395 <= select_ln214_fu_899_p3;
        shl_ln_reg_1400[15 : 8] <= shl_ln_fu_907_p3[15 : 8];
        sub40_i_reg_1364 <= sub40_i_fu_793_p2;
        sub_i_i_i_reg_1359 <= sub_i_i_i_fu_787_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd0))) begin
        add_ln1488_reg_1433 <= add_ln1488_fu_1035_p2;
        cmp12_i_reg_1418 <= cmp12_i_fu_1004_p2;
        icmp_ln1404_1_reg_1428 <= icmp_ln1404_1_fu_1030_p2;
        icmp_ln1404_reg_1423 <= icmp_ln1404_fu_1020_p2;
        or_ln1592_1_reg_1443 <= or_ln1592_1_fu_1064_p2;
        or_ln1592_2_reg_1448 <= or_ln1592_2_fu_1070_p2;
        or_ln1592_reg_1438 <= or_ln1592_fu_1052_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_hdata_flag_0_phi_fu_422_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd1))) begin
        hdata <= hdata_new_0_fu_296;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_new_0_fu_296 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_0554_lcssa561_fu_252 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_0556_lcssa564_fu_256 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_0558_lcssa567_fu_260 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd1))) begin
        rampStart <= add_ln705_fu_1081_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd1))) begin
        rampVal_1 <= rampVal_3_new_0_fu_324;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd1))) begin
        rampVal_2 <= rampVal_2_new_0_fu_280;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_new_0_fu_280 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_3_new_0_fu_324 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_3_reg_1410 <= y_fu_264;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write;
    end else begin
        bckgndYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_993_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Sel_fu_1010_p4 = {{y_fu_264[7:6]}};

assign add2_i_fu_705_p2 = (empty_fu_701_p1 + 14'd15);

assign add5_i_fu_735_p2 = (empty_72_fu_731_p1 + 14'd15);

assign add_i_fu_757_p2 = (empty_fu_701_p1 + 14'd7);

assign add_ln1404_fu_799_p2 = ($signed(loopHeight_cast16_fu_727_p1) + $signed(17'd131071));

assign add_ln1488_fu_1035_p2 = (rampStart + trunc_ln518_fu_989_p1);

assign add_ln518_fu_998_p2 = (y_fu_264 + 16'd1);

assign add_ln705_fu_1081_p2 = (motionSpeed + rampStart);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_422_p4 = hdata_flag_0_reg_418;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4 = rampVal_2_flag_0_reg_430;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4 = rampVal_3_flag_0_reg_406;

assign ap_ready = internal_ap_ready;

assign barHeight_cast_cast_fu_783_p1 = tmp_2_fu_773_p4;

assign barWidthMinSamples_fu_721_p2 = ($signed(p_cast_fu_711_p4) + $signed(10'd1023));

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din;

assign cmp126_i_fu_811_p2 = ((dpYUVCoef == 8'd0) ? 1'b1 : 1'b0);

assign cmp12_i_fu_1004_p2 = ((y_fu_264 != 16'd0) ? 1'b1 : 1'b0);

assign cmp141_i_fu_817_p2 = ((colorFormat != 8'd1) ? 1'b1 : 1'b0);

assign cmp2_i321_fu_629_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign cmp59_i_fu_805_p2 = ((dpDynamicRange == 8'd0) ? 1'b1 : 1'b0);

assign conv2_i_i10_i326_fu_635_p3 = ((cmp2_i321_fu_629_p2[0:0] == 1'b1) ? 8'd255 : 8'd76);

assign conv2_i_i10_i331_fu_649_p3 = ((cmp2_i321_fu_629_p2[0:0] == 1'b1) ? 8'd0 : 8'd149);

assign conv2_i_i10_i349_cast_cast_cast_cast_fu_665_p3 = ((cmp2_i321_fu_629_p2[0:0] == 1'b1) ? 3'd0 : 3'd5);

assign conv2_i_i_i333_cast_cast_fu_657_p3 = ((cmp2_i321_fu_629_p2[0:0] == 1'b1) ? 5'd0 : 5'd21);

assign conv2_i_i_i351_fu_673_p3 = ((cmp2_i321_fu_629_p2[0:0] == 1'b1) ? 8'd255 : 8'd107);

assign empty_72_fu_731_p1 = height[13:0];

assign empty_fu_701_p1 = width[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg;

assign icmp_fu_751_p2 = ((tmp_fu_741_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln1217_fu_915_p2 = ((colorFormat != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1404_1_fu_1030_p2 = ((add_ln1404_reg_1369 == zext_ln1404_fu_1026_p1) ? 1'b1 : 1'b0);

assign icmp_ln1404_fu_1020_p2 = ((y_fu_264 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1592_1_fu_1046_p2 = ((Sel_fu_1010_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln1592_2_fu_1058_p2 = ((Sel_fu_1010_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1592_fu_1040_p2 = ((Sel_fu_1010_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln518_fu_993_p2 = ((y_fu_264 == height) ? 1'b1 : 1'b0);

assign loopHeight_cast16_fu_727_p1 = height;

assign loopWidth_cast15_fu_697_p1 = width;

assign not_cmp2_i321_fu_643_p2 = (cmp2_i321_fu_629_p2 ^ 1'd1);

assign or_ln1592_1_fu_1064_p2 = (icmp_ln1592_2_fu_1058_p2 | icmp_ln1592_1_fu_1046_p2);

assign or_ln1592_2_fu_1070_p2 = (icmp_ln1592_fu_1040_p2 | icmp_ln1592_2_fu_1058_p2);

assign or_ln1592_fu_1052_p2 = (icmp_ln1592_fu_1040_p2 | icmp_ln1592_1_fu_1046_p2);

assign p_cast_fu_711_p4 = {{add2_i_fu_705_p2[13:4]}};

assign pix_val_V_5_fu_689_p3 = ((cmp2_i321_fu_629_p2[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign pix_val_V_fu_681_p3 = ((cmp2_i321_fu_629_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln214_fu_899_p3 = ((cmp2_i321_fu_629_p2[0:0] == 1'b1) ? rampStart : 8'd128);

assign shl_ln_fu_907_p3 = {{rampStart}, {8'd0}};

assign start_out = real_start;

assign sub40_i_fu_793_p2 = ($signed(loopWidth_cast15_fu_697_p1) + $signed(17'd131071));

assign sub_i_i_i_fu_787_p2 = ($signed(barHeight_cast_cast_fu_783_p1) + $signed(11'd2047));

assign tmp_2_fu_773_p4 = {{add5_i_fu_735_p2[13:4]}};

assign tmp_fu_741_p4 = {{colorFormat[7:1]}};

assign trunc_ln518_fu_989_p1 = y_fu_264[7:0];

assign zext_ln1212_fu_835_p1 = rampVal;

assign zext_ln1367_fu_851_p1 = vBarSel;

assign zext_ln1404_fu_1026_p1 = y_fu_264;

assign zext_ln1493_fu_859_p1 = hBarSel;

assign zext_ln1610_fu_875_p1 = hBarSel_3;

assign zext_ln1730_fu_887_p1 = vBarSel_1;

assign zext_ln518_fu_895_p1 = hBarSel_1;

always @ (posedge ap_clk) begin
    conv2_i_i10_i326_reg_1303[3:2] <= 2'b11;
    conv2_i_i10_i326_reg_1303[6] <= 1'b1;
    conv2_i_i10_i331_reg_1313[1] <= 1'b0;
    conv2_i_i10_i331_reg_1313[3:3] <= 1'b0;
    conv2_i_i10_i331_reg_1313[6:5] <= 2'b00;
    conv2_i_i_i333_cast_cast_reg_1318[1] <= 1'b0;
    conv2_i_i_i333_cast_cast_reg_1318[3] <= 1'b0;
    conv2_i_i10_i349_cast_cast_cast_cast_reg_1323[1] <= 1'b0;
    conv2_i_i_i351_reg_1328[1:0] <= 2'b11;
    conv2_i_i_i351_reg_1328[3:3] <= 1'b1;
    conv2_i_i_i351_reg_1328[6:5] <= 2'b11;
    pix_val_V_reg_1333[6:0] <= 7'b0000000;
    pix_val_V_5_reg_1338[7] <= 1'b1;
    shl_ln_reg_1400[7:0] <= 8'b00000000;
end

endmodule //v_tpg_0_tpgBackground
