// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module v_tpg_0_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ovrlayYUV_dout,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        ovrlayYUV_empty_n,
        ovrlayYUV_read,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        height,
        width,
        colorFormat,
        fid_in,
        fid,
        fid_ap_vld,
        field_id
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] ovrlayYUV_dout;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
input   ovrlayYUV_empty_n;
output   ovrlayYUV_read;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [15:0] height;
input  [15:0] width;
input  [7:0] colorFormat;
input  [0:0] fid_in;
output  [0:0] fid;
output   fid_ap_vld;
input  [15:0] field_id;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ovrlayYUV_read;
reg[0:0] fid;
reg fid_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] fidStored;
reg   [15:0] counter;
wire   [10:0] trunc_ln882_fu_183_p1;
reg   [10:0] trunc_ln882_reg_378;
wire   [10:0] empty_133_fu_187_p1;
reg   [10:0] empty_133_reg_383;
wire   [11:0] sub_fu_199_p2;
reg   [11:0] sub_reg_388;
wire   [0:0] cmp103_fu_205_p2;
reg   [0:0] cmp103_reg_393;
wire   [0:0] cmp19230_fu_211_p2;
reg   [0:0] cmp19230_reg_403;
wire   [0:0] switch_le_fu_223_p2;
reg   [0:0] switch_le_reg_407;
wire   [0:0] icmp_ln993_fu_229_p2;
reg   [0:0] icmp_ln993_reg_412;
wire   [0:0] icmp_ln993_1_fu_235_p2;
reg   [0:0] icmp_ln993_1_reg_417;
wire   [0:0] icmp_ln975_fu_245_p2;
reg   [0:0] icmp_ln975_reg_422;
wire   [10:0] i_2_fu_279_p2;
reg   [10:0] i_2_reg_430;
wire    ap_CS_fsm_state2;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_done;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_idle;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_ready;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ovrlayYUV_read;
wire   [23:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TDATA;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TVALID;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TREADY;
wire   [2:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TKEEP;
wire   [2:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TSTRB;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TUSER;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TLAST;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TID;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TDEST;
wire   [15:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_loc_1_out_o;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_loc_1_out_o_ap_vld;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_phi_ln991_out;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_phi_ln991_out_ap_vld;
wire   [15:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_ap_vld;
reg    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start_reg;
wire   [0:0] icmp_ln934_fu_274_p2;
wire    ap_CS_fsm_state3;
reg   [15:0] counter_loc_0_fu_110;
reg   [0:0] phi_ln991_loc_fu_114;
reg   [10:0] i_fu_98;
wire    ap_CS_fsm_state4;
reg    ap_block_state1;
reg   [0:0] empty_fu_102;
wire   [0:0] select_ln993_fu_324_p3;
reg   [0:0] sof_fu_106;
reg   [0:0] fid_preg;
wire   [11:0] zext_ln883_fu_191_p1;
wire   [15:0] empty_134_fu_217_p2;
wire   [0:0] and_ln993_fu_302_p2;
wire   [0:0] xor_ln1008_fu_312_p2;
wire   [0:0] or_ln993_fu_307_p2;
wire   [0:0] select_ln1006_fu_318_p3;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 fidStored = 1'd0;
#0 counter = 16'd0;
#0 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start_reg = 1'b0;
#0 fid_preg = 1'd0;
end

v_tpg_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start),
    .ap_done(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_done),
    .ap_idle(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_idle),
    .ap_ready(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_ready),
    .sof(sof_fu_106),
    .width_load_cast1(empty_133_reg_383),
    .ovrlayYUV_dout(ovrlayYUV_dout),
    .ovrlayYUV_num_data_valid(5'd0),
    .ovrlayYUV_fifo_cap(5'd0),
    .ovrlayYUV_empty_n(ovrlayYUV_empty_n),
    .ovrlayYUV_read(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ovrlayYUV_read),
    .icmp_ln975(icmp_ln975_reg_422),
    .m_axis_video_TDATA(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TDATA),
    .m_axis_video_TVALID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TVALID),
    .m_axis_video_TREADY(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TREADY),
    .m_axis_video_TKEEP(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TSTRB),
    .m_axis_video_TUSER(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TUSER),
    .m_axis_video_TLAST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TLAST),
    .m_axis_video_TID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TID),
    .m_axis_video_TDEST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TDEST),
    .sub(sub_reg_388),
    .counter_loc_1_out_i(counter_loc_0_fu_110),
    .counter_loc_1_out_o(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_loc_1_out_o),
    .counter_loc_1_out_o_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_loc_1_out_o_ap_vld),
    .phi_ln991_out(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_phi_ln991_out),
    .phi_ln991_out_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_phi_ln991_out_ap_vld),
    .counter(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter),
    .counter_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fid_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd1))) begin
            fid_preg <= empty_fu_102;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start_reg <= 1'b0;
    end else begin
        if (((cmp19230_reg_403 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd0))) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_ready == 1'b1)) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_loc_0_fu_110 <= counter;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_loc_1_out_o_ap_vld == 1'b1))) begin
        counter_loc_0_fu_110 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_fu_102 <= fidStored;
    end else if (((cmp19230_reg_403 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        empty_fu_102 <= select_ln993_fu_324_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_98 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i_fu_98 <= i_2_reg_430;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_fu_106 <= 1'd1;
    end else if (((cmp19230_reg_403 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sof_fu_106 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp103_reg_393 <= cmp103_fu_205_p2;
        cmp19230_reg_403 <= cmp19230_fu_211_p2;
        empty_133_reg_383 <= empty_133_fu_187_p1;
        icmp_ln975_reg_422 <= icmp_ln975_fu_245_p2;
        icmp_ln993_1_reg_417 <= icmp_ln993_1_fu_235_p2;
        icmp_ln993_reg_412 <= icmp_ln993_fu_229_p2;
        sub_reg_388 <= sub_fu_199_p2;
        switch_le_reg_407 <= switch_le_fu_223_p2;
        trunc_ln882_reg_378 <= trunc_ln882_fu_183_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter_ap_vld == 1'b1))) begin
        counter <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_counter;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd1))) begin
        fidStored <= empty_fu_102;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_2_reg_430 <= i_2_fu_279_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_phi_ln991_out_ap_vld == 1'b1))) begin
        phi_ln991_loc_fu_114 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_phi_ln991_out;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd1))) begin
        fid = empty_fu_102;
    end else begin
        fid = fid_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd1))) begin
        fid_ap_vld = 1'b1;
    end else begin
        fid_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ovrlayYUV_read = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ovrlayYUV_read;
    end else begin
        ovrlayYUV_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((cmp19230_reg_403 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_274_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln993_fu_302_p2 = (phi_ln991_loc_fu_114 & icmp_ln993_reg_412);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign cmp103_fu_205_p2 = ((field_id == 16'd3) ? 1'b1 : 1'b0);

assign cmp19230_fu_211_p2 = ((empty_133_fu_187_p1 == 11'd0) ? 1'b1 : 1'b0);

assign empty_133_fu_187_p1 = width[10:0];

assign empty_134_fu_217_p2 = (field_id | 16'd1);

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_ap_start_reg;

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TREADY = (m_axis_video_TREADY & ap_CS_fsm_state3);

assign i_2_fu_279_p2 = (i_fu_98 + 11'd1);

assign icmp_ln934_fu_274_p2 = ((i_fu_98 == trunc_ln882_reg_378) ? 1'b1 : 1'b0);

assign icmp_ln975_fu_245_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln993_1_fu_235_p2 = ((empty_134_fu_217_p2 != 16'd1) ? 1'b1 : 1'b0);

assign icmp_ln993_fu_229_p2 = ((field_id != 16'd0) ? 1'b1 : 1'b0);

assign m_axis_video_TDATA = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TDATA;

assign m_axis_video_TDEST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TDEST;

assign m_axis_video_TID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TID;

assign m_axis_video_TKEEP = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TKEEP;

assign m_axis_video_TLAST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TLAST;

assign m_axis_video_TSTRB = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TSTRB;

assign m_axis_video_TUSER = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TUSER;

assign m_axis_video_TVALID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_155_m_axis_video_TVALID;

assign or_ln993_fu_307_p2 = (icmp_ln993_1_reg_417 | and_ln993_fu_302_p2);

assign select_ln1006_fu_318_p3 = ((cmp103_reg_393[0:0] == 1'b1) ? xor_ln1008_fu_312_p2 : fid_in);

assign select_ln993_fu_324_p3 = ((switch_le_reg_407[0:0] == 1'b1) ? or_ln993_fu_307_p2 : select_ln1006_fu_318_p3);

assign sub_fu_199_p2 = ($signed(zext_ln883_fu_191_p1) + $signed(12'd4095));

assign switch_le_fu_223_p2 = ((field_id < 16'd3) ? 1'b1 : 1'b0);

assign trunc_ln882_fu_183_p1 = height[10:0];

assign xor_ln1008_fu_312_p2 = (phi_ln991_loc_fu_114 ^ 1'd1);

assign zext_ln883_fu_191_p1 = empty_133_fu_187_p1;

endmodule //v_tpg_0_MultiPixStream2AXIvideo
